import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { Layout } from "./components/Layout";

export const metadata: Metadata = {
  title: "Spoondog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className="font-roboto text-dark">
        <Layout>{children}</Layout>
        <SpeedInsights />
      </body>
    </html>
  );
}
