import { CareHygieneService } from "./CareHygieneDataInterface";

export const careServicesData: CareHygieneService[] = [
  {
    title: "Rozczesywanie",
    smallTitle: "Na czym polega zabieg rozczesywania?",
    description1:
      "Rozczesywanie sierści to usuwanie sfilcowań i kołtunów, jakie powstały w sierści psów średniowłosych i długowłosych przy jak najmniejszym ubytku włosa. ",
    description2:
      "Zabieg wykonywany jest ręcznie przy użyciu grzebieni oraz preparatów ułatwiających rozczesywanie i środków zapobiegających łamaniu się włosa.",
    description3: "",
    price: "Cena",
    mini: "miniaturki (do 3 kg) -  ",
    miniPrice: "50 zł",
    small: "rasy małe -  ",
    smallPrice: "50 zł",
    medium: "rasy średnie -  ",
    mediumPrice: "50 zł",
    big: "rasy duże -  ",
    bigPrice: "80 zł",
    cat: "koty -  ",
    catPrice: "50 zł",
    src1: "/images/careServices/combingDog1.jpg",
    src2: "/images/careServices/combingDog2.jpg",
    alt: "Zdjęcie psa podczas rozczesywania",
  },
  {
    title: "Strzyżenie",
    smallTitle: "Na czym polega zabieg strzyżenia?",
    description1:
      "Strzyżenie psa polega na to skracaniu włosa na określoną długość przy użyciu maszynki elektrycznej lub nożyczek. Zabieg odpowiedni dla niemal wszystkich psów, choć w przypadku psów szorstkowłosych, szczególnie wystawowych lub tych, które mają przed sobą karierę wystawową, strzyżenie zwykle znacznie obniża jakość i strukturę włosa.",
    description2: "",
    description3: "",
    price: "Cena",
    mini: "miniaturki (do 3 kg) -  ",
    miniPrice: "50 zł",
    small: "rasy małe -  ",
    smallPrice: "50 zł",
    medium: "rasy średnie -  ",
    mediumPrice: "50 zł",
    big: "rasy duże -  ",
    bigPrice: "80 zł",
    cat: "koty -  ",
    catPrice: "50 zł",
    src1: "/images/careServices/haircutDog1.jpg",
    src2: "/images/careServices/haircutDog2.jpg",
    alt: "Zdjęcie psa podczas strzyżenia",
  },
  {
    title: "Trymowanie",
    smallTitle: "Na czym polega zabieg trymowania?",
    description1:
      "Zabieg trymowania polega na ręcznym usuwaniu wyłącznie martwych włosów, bez naruszania żywych. Polega na pociąganiu końców włosów, by usunąć z torebek włosowych tylko te, które są już martwe. Usuwanie martwych włosów nie szkodzi psu i zupełnie go nie boli. Przerzedzenie w ten sposób fryzury ułatwia wzrost nowych włosów i zapobiega powstawianiu filców czy kołtunów, wzmaga też nasycenie barw na psach kolorowych i stanowi zdrowy i ożywczy masaż skóry.",
    description2: "",
    description3: "",
    price: "Cena",
    mini: "miniaturki (do 3 kg) -  ",
    miniPrice: "50 zł",
    small: "rasy małe -  ",
    smallPrice: "50 zł",
    medium: "rasy średnie -  ",
    mediumPrice: "50 zł",
    big: "rasy duże -  ",
    bigPrice: "80 zł",
    cat: "koty -  ",
    catPrice: "50 zł",
    src1: "/images/careServices/trimmingDog1.jpg",
    src2: "/images/careServices/trimmingDog2.jpg",
    alt: "Zdjęcie psa podczas trymowania",
  },
];
