import { CareHygieneService } from "./CareHygieneDataInterface";

export const hygieneServicesData: CareHygieneService[] = [
  {
    id: "bath",
    title: "Kąpiel",
    smallTitle: "Na czym polega zabieg kąpieli?",
    description1:
      "Częstotliwość kąpieli psa zależy od wieku, rasy i warunków życia (domowy czy podwórkowy). Przez pierwsze dwa miesiące szczenięta przemywaj wilgotną gąbką. Pierwszą kąpiel przeprowadź po czterech miesiącach, jeśli to konieczne.",
    description2:
      "Psy domowe można kąpać co dwa tygodnie odpowiednimi kosmetykami. Regularne kąpiele zapobiegają nieprzyjemnym zapachom i dbają o zdrowie sierści.",
    description3:
      "Psy podwórkowe kąp nie częściej niż 2-3 razy do roku, aby nie zniszczyć naturalnej bariery ochronnej skóry. Unikaj szamponów owadobójczych i ludzkich kosmetyków; używaj odpowiednich preparatów na pasożyty.",
    price: "Cena",
    mini: "miniaturki (do 3 kg) -  ",
    miniPrice: "50 zł",
    small: "rasy małe -  ",
    smallPrice: "50 zł",
    medium: "rasy średnie -  ",
    mediumPrice: "50 zł",
    big: "rasy duże -  ",
    bigPrice: "80 zł",
    cat: "koty -  ",
    catPrice: "50 zł",
    src1: "/images/hygieneServices/bathDog1.jpg",
    src2: "/images/hygieneServices/bathDog2.jpg",
    alt: "Zdjęcie psa podczas kąpieli",
  },
  {
    id: "ears",
    title: "Higiena uszu",
    smallTitle: "Na czym polega zabieg higieny uszu?",
    description1:
      "Konieczne jest usuwanie włosa który rośnie we wewnątrz ucha, nagromadzony włos może być przyczyną zapalenia ucha i innych chorób nieprzyjemnych dla naszego pupila oraz kosztownych w leczeniu dla właściciela (dotyczy ras posiadających włosy).",
    description2: "",
    description3: "",
    price: "Cena",
    mini: "miniaturki (do 3 kg) -  ",
    miniPrice: "50 zł",
    small: "rasy małe -  ",
    smallPrice: "50 zł",
    medium: "rasy średnie -  ",
    mediumPrice: "50 zł",
    big: "rasy duże -  ",
    bigPrice: "80 zł",
    cat: "koty -  ",
    catPrice: "50 zł",
    src1: "/images/hygieneServices/earsDog1.jpg",
    src2: "/images/hygieneServices/earsDog2.jpg",
    alt: "Zdjęcie psa podczas usuwania kamienia nazębnego",
  },
  {
    id: "claws",
    title: "Przycięcie pazurów",
    smallTitle: "Na czym polega zabieg przycięcia pazurów?",
    description1:
      "Zabieg ten polega na przycięciu pazurków u zwierząt tak aby nie uszkodzić nerwu paznokcia. Należy w odpowiedni sposób skrócić pazurki.",
    description2:
      "Odradzam wykonywania tego samemu, ponieważ raz zranione zwierzę będzie miało uraz już na zawsze.",
    description3: "",
    price: "Cena",
    mini: "miniaturki (do 3 kg) -  ",
    miniPrice: "50 zł",
    small: "rasy małe -  ",
    smallPrice: "50 zł",
    medium: "rasy średnie -  ",
    mediumPrice: "50 zł",
    big: "rasy duże -  ",
    bigPrice: "80 zł",
    cat: "koty -  ",
    catPrice: "50 zł",
    src1: "/images/hygieneServices/clawsDog1.jpg",
    src2: "/images/hygieneServices/clawsDog2.jpg",
    alt: "Zdjęcie psa podczas przycinania pazurków",
  },
  {
    id: "teeth",
    title: "Usuwanie kamienia nazębnego metodą ultradźwięków",
    smallTitle: "Na czym polega zabieg usuwania kamienia nazębnego?",
    description1:
      "Usuwanie kamienia nazębnego u psów metodą ultradźwięków polega na użyciu specjalnego urządzenia, które emituje fale ultradźwiękowe. Fale te powodują wibracje, które skutecznie rozbijają i usuwają kamień nazębny z powierzchni zębów. Zabieg jest bezbolesny i precyzyjny, minimalizując ryzyko uszkodzenia szkliwa. Najczęściej wykonuje się go pod znieczuleniem ogólnym, aby zapewnić psu komfort i bezpieczeństwo podczas procedury.",
    description2: "",
    description3: "",
    price: "Cena",
    mini: "miniaturki (do 3 kg) -  ",
    miniPrice: "50 zł",
    small: "rasy małe -  ",
    smallPrice: "50 zł",
    medium: "rasy średnie -  ",
    mediumPrice: "50 zł",
    big: "rasy duże -  ",
    bigPrice: "80 zł",
    cat: "koty -  ",
    catPrice: "50 zł",
    src1: "/images/hygieneServices/teethDog1.jpg",
    src2: "/images/hygieneServices/teethDog2.jpg",
    alt: "Zdjęcie psa podczas usuwania kamienia nazębnego",
  },
];
