export const PricesData = [
  {
    imageSrc: "/images/pricesDogXS.png",
    title: "Miniaturki",
    subTitle: "(do 3 kg)",
    services: [
      { name: "Strzyżenie", price: "60 zł + kąpiel 10zł" },
      { name: "Rozczesywanie", price: "100 zł/h" },
      { name: "Trymowanie", price: "150 zł/h" },
      { name: "Kąpiel", price: "30 - 50 zł" },
      { name: "Czyszczenie uszu", price: "50 zł/h" },
      { name: "Pazurki", price: "10 zł" },
      { name: "Zdejmowanie kamienia z zębów", price: "50 zł/h" },
      { name: "Komplet (strzyżenie, kąpiel, pazurki, uszy)", price: "60 zł" },
    ],
  },
  {
    imageSrc: "/images/pricesDogS.png",
    title: "Rasy małe",
    services: [
      { name: "Strzyżenie", price: "80 - 100 zł + kąpiel 10 - 20 zł" },
      { name: "Rozczesywanie", price: "100 zł/h" },
      { name: "Trymowanie", price: "150 zł/h" },
      { name: "Kąpiel", price: "30 - 80 zł" },
      { name: "Czyszczenie uszu", price: "50 zł/h" },
      { name: "Pazurki", price: "10 zł" },
      { name: "Zdejmowanie kamienia z zębów", price: "50 zł/h" },
      { name: "Komplet (strzyżenie, kąpiel, pazurki, uszy)", price: "60 zł" },
    ],
  },
  {
    imageSrc: "/images/pricesDogM.png",
    title: "Rasy średnie",
    services: [
      { name: "Strzyżenie", price: "100 - 150 zł + kąpiel 10- 30 zł" },
      { name: "Rozczesywanie", price: "100 zł/h" },
      { name: "Trymowanie", price: "150 zł/h" },
      { name: "Kąpiel", price: "40 - 100 zł" },
      { name: "Czyszczenie uszu", price: "50 zł/h" },
      { name: "Pazurki", price: "10 zł" },
      { name: "Zdejmowanie kamienia z zębów", price: "50 zł/h" },
      { name: "Komplet (strzyżenie, kąpiel, pazurki, uszy)", price: "60 zł" },
    ],
  },
  {
    imageSrc: "/images/pricesDogL.png",
    title: "Rasy duże",
    services: [
      { name: "Strzyżenie", price: "ceny ustalane indywidualnie" },
      { name: "Rozczesywanie", price: "100 zł/h" },
      { name: "Trymowanie", price: "150 zł/h" },
      { name: "Kąpiel", price: "70 - 200 zł" },
      { name: "Czyszczenie uszu", price: "50 zł/h" },
      { name: "Pazurki", price: "10 zł" },
      { name: "Zdejmowanie kamienia z zębów", price: "50 zł/h" },
      { name: "Komplet (strzyżenie, kąpiel, pazurki, uszy)", price: "60 zł" },
    ],
  },
];


// export const PricesData: PriceData[] = [
//   services: [
//     { name: "Strzyżenie" },
//     { name: "Rozczesywanie" },
//     { name: "Trymowanie" },
//     { name: "Kąpiel" },
//     { name: "Czyszczenie uszu" },
//     { name: "Pazurki" },
//     { name: "Zdejmowanie kamienia z zębów" },
//     { name: "Komplet (strzyżenie, kąpiel, pazurki, uszy)" },
//   ],
//   prices: [
//     {
//       imageSrc: "/images/pricesDogXS.png",
//       title: "Miniaturki",
//       subTitle: "(do 3 kg)",
//       servicePrices: [
//         "60 zł + kąpiel 10 zł",
//         "100 zł/h",
//         "150 zł/h",
//         "30 - 50 zł",
//         "50 zł/h",
//         "10 zł",
//         "50 zł/h",
//         "60 zł",
//       ],
//     },
//     {
//       imageSrc: "/images/pricesDogS.png",
//       title: "Rasy małe",
//       servicePrices: [
//         "80 - 100 zł + kąpiel 10 - 20 zł",
//         "100 zł/h",
//         "150 zł/h",
//         "30 - 80 zł",
//         "50 zł/h",
//         "10 zł",
//         "50 zł/h",
//         "60 zł",
//       ],
//     },
//     {
//       imageSrc: "/images/pricesDogM.png",
//       title: "Rasy średnie",
//       servicePrices: [
//         "100 - 150 zł + kąpiel 10 - 30 zł",
//         "100 zł/h",
//         "150 zł/h",
//         "40 - 100 zł",
//         "50 zł/h",
//         "10 zł",
//         "50 zł/h",
//         "60 zł",
//       ],
//     },
//     {
//       imageSrc: "/images/pricesDogL.png",
//       title: "Rasy duże",
//       servicePrices: [
//         "ceny ustalane indywidualnie",
//         "100 zł/h",
//         "150 zł/h",
//         "70 - 200 zł",
//         "50 zł/h",
//         "10 zł",
//         "50 zł/h",
//         "60 zł",
//       ],
//     },
//   ],
// ];
